---
    - name: install HAproxy
      yum:
        name: haproxy
        state: present

    - name: copy config file
      template:
        src: ./roles/haproxy/templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      notify: restart haproxy
#    - name: start haproxy   
#      service:
#        name: haproxy
#        state: started


      
